nh os repl: init
viperML/nh pull request #171
Opened 2024-11-14 12:48 UTC by NotAShelf

Adds a repl subcommand for `nh os` which puts the user into a repl with the active nixosConfiguration loaded. Equivalent of `nix repl .#nixosConfiguration.$HOSTNAME` or entering nix repl and running `:lf nixosConfigurations.<hostname>`.

Things to maybe do:
1. Implement `nh home repl` (I really don't want to)
2. Fall back to a nix repl with `nixosConfigurations` if hostname cannot be get

2024-11-14 12:49 UTC, NotAShelf commented
Sorta fixes #66

2024-11-14 12:58 UTC, viperML requested changes

2024-11-14 12:58 UTC, viperML commented on src/nixos.rs
> +            hostname::get()
This should use self.hostname if it's not None

2024-11-15 08:39 UTC, viperML approved these changes

2024-11-15 09:17 UTC, NotAShelf commented
I should probably bump version in Cargo.toml

2024-11-15 09:26 UTC, merged