Test switching to darwin configuration
viperML/nh pull request #187
Opened 2024-12-01 23:23 UTC by ToyVo

Solves #182, I've also addressed a bug that I forgot about when I first implemented the darwin functionality involving how sudo behaves on mac.

The macos runners for github actions use minutes at 10x the rate of linux runners, and the version doesn't effect it, so I went for latest.

2024-12-02 09:01 UTC, viperML requested changes

2024-12-02 09:01 UTC, viperML commented on flake.nix
> +    nix-darwin = {
I don't want this flake to depend on nix-darwin, as it's only used for tests.

2024-12-02 09:01 UTC, viperML commented on src/commands.rs
> +            let cmd = Exec::cmd("sudo").args(
Why is this needed?

2024-12-02 09:12 UTC, viperML requested changes

2024-12-02 09:12 UTC, viperML commented on src/clean.rs
> +                #[cfg(not(target_os = "macos"))]
As an stylistic change I'd rather write:

```rust
    if cfg!(target_os = "macos") {
        // macos path
    } else {
        // generic path
    }
```

2024-12-05 04:46 UTC, ToyVo commented on src/commands.rs
> +            let cmd = Exec::cmd("sudo").args(
When invoking sudo on macos we would get errors in the console something along the lines of not owning the home directory
https://github.com/ToyVo/nh_plus/issues/5

```
DEBUG nh::commands:56: cmd=Exec { /usr/bin/sudo nix-env --profile /nix/var/nix/profiles/system --set /var/folders/xm/t9x8767d1p73___d71x35j8r0000gn/T/nh-os-mWyem4/result }
warning: $HOME ('/Users/caleb') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
```

Taken from darwin-rebuild, we could just not support 10.13 and just assume the flag is always there. https://github.com/LnL7/nix-darwin/blob/master/pkgs/nix-tools/darwin-rebuild.sh#L24-L34

2024-12-05 14:13 UTC, ToyVo commented
@viperML I've fixed up these few items

2024-12-06 07:34 UTC, merged

2024-12-06 07:55 UTC, Parsifa1 commented
It's weird, it seems that `@result` will still be generated in `pwd` when using `nh darwin switch`